#-------------------------------
# General Site Settings

menu:
- {name: 'About', url: 'pages/about.html'}
- {name: '2D', url: 'projects/2Dwork.html'}
- {name: '3D', url: 'projects/3Dwork.html'}
- {name: 'Other Projects', url: 'projects/Other_Projects.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Art by Louis Snow'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # About me

  My name is Louis, and I make art and illustrations. Sometimes in 2D, sometimes in 3D! I'm keen on practicing with new styles and mediums to expand my range as an artist, to make anything possible. Visually, of course.
  
  # Site Credits
  
  Special thanks to Joe and Robin for helping me set this site up. It was created with the [Portfolio Jekyll Theme](https://github.com/LeNPaul/portfolio-jekyll-theme).

contact: >
  # Contact

  You may contact me [through my email](mailto:losn0807@gmail.com) if you would like to ask about a commission or if there's anything about my work that you'd like to know!

#-------------------------------
# Work Section

projects:
- {name: '2D Work', folder: '2Dwork', file: 'projects/2Dwork.html'}
- {name: '3D Work', folder: '3Dwork', file: 'projects/3Dwork.html'}
- {name: 'Other Projects', folder: 'Other_Projects', file: 'projects/Other_Projects.html'}

#-------------------------------
# Contact Section

#social:
#- {icon: 'twitter', link: '#'}
#- {icon: 'instagram', link: '#'}
#- {icon: 'github', link: '#'}
#- {icon: 'linkedin', link: '#'}
#- {icon: 'envelope', link: 'mailto:#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
